// <auto-generated />
using System;
using Brenda.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Brenda.Infrastructure.Migrations
{
    [DbContext(typeof(BrendaDbContext))]
    [Migration("20260709133038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Brenda.Core.Models.BlenderVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutablePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutablePath")
                        .IsUnique();

                    b.ToTable("BlenderVersions");
                });

            modelBuilder.Entity("Brenda.Core.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOpenedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainBlendFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PinnedBlenderVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath")
                        .IsUnique();

                    b.HasIndex("PinnedBlenderVersionId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Brenda.Core.Models.Project", b =>
                {
                    b.HasOne("Brenda.Core.Models.BlenderVersion", "PinnedBlenderVersion")
                        .WithMany()
                        .HasForeignKey("PinnedBlenderVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PinnedBlenderVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
